<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zoriqo.Application\Zoriqo.Application.csproj" />
    <ProjectReference Include="..\Zoriqo.Domain\Zoriqo.Domain.csproj" />
  </ItemGroup>

</Project>
